'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")>  _
Partial Friend NotInheritable Class Settings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()),Settings)
    
    Public Shared ReadOnly Property [Default]() As Settings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Data Source=KR2012\SQLEXPRESS;Initial Catalog=ProHelp;Integrated Security=True")>  _
    Public ReadOnly Property ProHelpConnectionString() As String
        Get
            Return CType(Me("ProHelpConnectionString"),String)
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute(".\MSSQLLocalDB::.\SQLExpress")>  _
    Public Property ProHelpServerTest() As String
        Get
            Return CType(Me("ProHelpServerTest"),String)
        End Get
        Set
            Me("ProHelpServerTest") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Initial Catalog=ProHelp;Integrated Security=True")>  _
    Public Property ProHelpConnectionSuffix() As String
        Get
            Return CType(Me("ProHelpConnectionSuffix"),String)
        End Get
        Set
            Me("ProHelpConnectionSuffix") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ProHelpConnectionUser() As String
        Get
            Return CType(Me("ProHelpConnectionUser"),String)
        End Get
        Set
            Me("ProHelpConnectionUser") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ProHelpServerUser() As String
        Get
            Return CType(Me("ProHelpServerUser"),String)
        End Get
        Set
            Me("ProHelpServerUser") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("No")>  _
    Public Property ProHelpDebug() As String
        Get
            Return CType(Me("ProHelpDebug"),String)
        End Get
        Set
            Me("ProHelpDebug") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("%DOCUMENTS%\Kairos\Music for Parklea\MASTERS")>  _
    Public Property ProHelpMasterFolder() As String
        Get
            Return CType(Me("ProHelpMasterFolder"),String)
        End Get
        Set
            Me("ProHelpMasterFolder") = value
        End Set
    End Property
End Class
